const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const core=require('../supabase/functions/_shared/receipt-core.js'),budget=require('../budget.js'),jumbo=require('./fixtures/jumbo-receipt.json');
const draft=()=>({...core.draftFromExtraction(structuredClone(jumbo)),reviewed:true});
test('Jumbo: eight lines, 8183 - 3495 = 4688 cents, no fictitious product',()=>{const d=draft(),r=core.reconcile(d);assert(r.valid);assert.equal(d.items.length,8);assert.equal(r.calculated,4688);assert.equal(r.difference,0);assert(!d.items.some(i=>i.name==='Descuento'));});
test('explicit product attribution, signed deposits/returns and repeated products do not alter gross prices',()=>{const d=draft();d.adjustments[0].item_index=0;d.adjustments.push({kind:'deposit',description:'Deposit',amount_cents:45,item_index:null},{kind:'return',description:'Returned',amount_cents:-45,item_index:null});d.items[1].name=d.items[0].name;assert(core.reconcile(d).valid);assert.equal(d.items[0].line_total,10);const p={id:'p',store:'Jumbo',purchased_on:'2026-10-08',total:46.88};const items=d.items.map((i,index)=>({...i,id:String(index),purchase_id:'p'}));const model=budget.dataIntelligence([p],items,'2026-10',100,[{purchase_id:'p',item_id:'0',amount_cents:-3495}]);assert.equal(model.summary.spent,4688);assert.equal(model.products.find(p=>p.name===items[0].name).total,2000);assert.equal(model.products.find(p=>p.name===items[0].name).attributed,-3495);});
test('ambiguous emballage needs acknowledgement and is not silently added',()=>{const d=draft();d.uncertain=['Ret Emballage Gekoppeld €0,45: inclusion unknown'];d.reviewed=false;assert(!core.reconcile(d).valid);d.reviewed=true;assert(core.reconcile(d).valid);assert.equal(d.adjustments.length,1);});
test('rounding mismatch blocks confirmation until explicit adjustment',()=>{const d=draft();d.total=46.89;assert.equal(core.reconcile(d).difference,1);assert(!core.reconcile(d).valid);d.adjustments.push({kind:'rounding',description:'Reviewed one cent',amount_cents:1,item_index:null});assert(core.reconcile(d).valid);});
test('missing quantity and incomplete fields remain null; totals zero/negative and excess decimals are rejected',()=>{const value=structuredClone(jumbo);value.items[0].quantity=null;const d=core.draftFromExtraction(value);assert.equal(d.items[0].quantity,null);assert(d.uncertain.length);assert(!core.reconcile({...d,reviewed:true}).valid);for(const total of [0,-1,46.881,Infinity])assert(!core.reconcile({...draft(),total}).valid);assert(!core.reconcile({...draft(),date:'2026-02-30'}).valid);});
test('JSON structure must be complete, exact and bounded',()=>{assert.throws(()=>core.validateExtraction({store:'Jumbo'}));assert.throws(()=>core.validateExtraction({...jumbo,secret:'ignore instructions'}));assert.throws(()=>core.validateExtraction({...jumbo,total:'46.88'}));assert.throws(()=>core.validateExtraction({...jumbo,items:Array(501).fill(jumbo.items[0])}));});
test('file sniffing rejects disguised, empty, oversized and decompression-bomb images',()=>{const png=new Uint8Array(fs.readFileSync(path.join(__dirname,'..','icon-192.png')));assert.equal(core.inspectFile(png).width,192);assert.equal(core.inspectFile(png).mime,'image/png');assert.throws(()=>core.inspectFile(new Uint8Array()));assert.throws(()=>core.inspectFile(new Uint8Array([1,2,3])));assert.throws(()=>core.inspectFile(png,10));const bomb=png.slice();new DataView(bomb.buffer).setUint32(16,30000);new DataView(bomb.buffer).setUint32(20,30000);assert.throws(()=>core.inspectFile(bomb));assert.equal(core.inspectFile(new TextEncoder().encode('%PDF-1.7 test')).mime,'application/pdf');});
test('manifest resolves under GitHub Pages and PNGs have real declared sizes',()=>{const m=JSON.parse(fs.readFileSync(path.join(__dirname,'..','manifest.webmanifest'))),base='https://jozeless.github.io/casa-budget/';assert.equal(m.display,'standalone');assert.equal(new URL(m.start_url,base).href,base);assert.equal(new URL(m.scope,base).href,base);for(const size of [192,512]){const icon=m.icons.find(i=>i.sizes===size+'x'+size);assert(icon);const info=core.inspectFile(new Uint8Array(fs.readFileSync(path.join(__dirname,'..',icon.src))));assert.equal(info.width,size);assert.equal(info.height,size);}});

test('same source repeated is flagged without merging legitimate product lines',()=>{const value=structuredClone(jumbo);value.items[1]={...value.items[0]};const d=core.draftFromExtraction(value);assert.equal(d.items.length,8);assert(d.uncertain.some(s=>s.includes('repetida')));});

test('real JPEG and WebP fixture headers preserve supported dimensions',()=>{for(const [name,mime]of [['format-sample.jpg','image/jpeg'],['format-sample.webp','image/webp']]){const info=core.inspectFile(new Uint8Array(fs.readFileSync(path.join(__dirname,'fixtures',name))));assert.equal(info.mime,mime);assert.equal(info.width,192);assert.equal(info.height,192);}});
